CREATE DATABASE MARCH_EMPDB;
USE MARCH_EMPDB;

CREATE TABLE EMPLOYEE(
	EMPID INT IDENTITY(1,1) PRIMARY KEY,
	EMPNAME VARCHAR(30) NOT NULL,
	AGE INT  NOT NULL,
	EMAIL VARCHAR(30)  NOT NULL,
	DOB DATE  NOT NULL,
	PHNO   VARCHAR(15) NOT NULL
);
INSERT INTO EMPLOYEE 
VALUES (
	'Hansini', 
	21,
	'hansinikb@gmail.com',
	'2003-07-01',
	8861519925
);
INSERT INTO EMPLOYEE 
VALUES (
	'xyz', 
	21,
	'xyz@gmail.com',
	'2003-07-01',
	8861519925
);
SELECT * FROM ATTENDANCE;
CREATE TABLE ATTENDANCE(
	ATTENDANCEID INT IDENTITY(1,1) PRIMARY KEY,
	EMPID INT REFERENCES EMPLOYEE(EMPID),
	ATTDATE DATE NOT NULL,
	INTIME DATETIME NOT NULL,
	OUTTIME DATETIME NOT NULL
);

INSERT INTO ATTENDANCE (EMPID, ATTDATE, INTIME, OUTTIME)
VALUES (
    9,  
    '2024-03-01',
    '2024-03-01 09:00:00',
    '2024-03-01 17:00:00'
);

INSERT INTO ATTENDANCE (EMPID, ATTDATE, INTIME, OUTTIME)
VALUES (
    1002,  
    '2024-03-01',
    '2024-03-01 09:15:00',
    '2024-03-01 17:30:00'
);

CREATE TABLE LIBRARY (
    BOOKID INT PRIMARY KEY, 
    CATEGORY VARCHAR(30), 
    AUTHOR VARCHAR(30),
	BOOKNAME VARCHAR(30)
);
INSERT INTO LIBRARY (BOOKID, BOOKNAME, CATEGORY, AUTHOR) VALUES (1, 'The Courage to Be Disliked', 'Philosophy', 'Ichiro Kishimi & Fumitake Koga');
INSERT INTO LIBRARY (BOOKID, BOOKNAME, CATEGORY, AUTHOR) VALUES (2, 'Geronimo', 'Kids books ', 'Geronimo Stilton');
INSERT INTO LIBRARY (BOOKID, BOOKNAME, CATEGORY, AUTHOR) VALUES (3, 'Famous Five', 'Adventure', 'Enid Blyton');
INSERT INTO LIBRARY (BOOKID, BOOKNAME, CATEGORY, AUTHOR) VALUES (4, 'Harry Potter', 'Fantasy', 'J.K. Rowling');

CREATE TABLE TRAVEL (
    EMPID INT REFERENCES EMPLOYEE(EmpID),
    HOMEADDRESS VARCHAR(255),
    SHIFTTIME TIME,
);

INSERT INTO TRAVEL (EMPID, HOMEADDRESS, SHIFTTIME) VALUES 
(1002, 'Koramangala', '08:00:00'),
(9, 'Indiranagar', '09:00:00');

select * from library;

select * from EMPLOYEE;